#!/bin/sh
# starts N instances of a job
# ex.: pgo jubba.py 8
#      will start eight instances of python script jubba.py

function usage
{
  echo "Usage: pgo pyfile.py [num [-nb]"
  echo "           num - Number to start"
  echo "           -nb - No backup of script"
  exit 1
}

# check number of args
if [ $# -gt 3 ]; then
    usage
    exit 1
fi
if [ $# -lt 1 ]; then
    usage
    exit 1
fi


# look for runmfile in current dir
SH_PATH=`dirname $0`
if [ "$SH_PATH" = "" ]; then
    SH_PATH=`dirname \`which $0\``
fi
SH_SCRIPT=${SH_PATH}/runpyfile.sh

BACK_DIR=runs
PYFILE=$1
PNAME=`expr substr \`basename $PYFILE\` 1 15`
PROCS=$2
if [ $# -lt 2 ]; then
    PROCS=1
fi


# save history
if [ "$3" != "-nb" ]; then
    echo Making backup:
    mkdir -p $BACK_DIR
    echo cp $PYFILE runs/${PYFILE}.`date +%y%b%d_%H%M`
    cp $PYFILE runs/${PYFILE}.`date +%y%b%d_%H%M`
fi


# start scripts
# node_list=("node19" "node20" "node21" "node22" "node23")  # "node17" "node18" "node19" "node20" "node21"
node_list=("node33" "node34" "node35" "node36" "node37")
echo Starting $PROCS script\(s\):
for node_idx in "${!node_list[@]}"; do
    node=${node_list[$node_idx]}
    echo $node
    for i in `seq 1 $PROCS`; do
        echo $i
        # add email notification on last submission
        if [[ $node_idx -eq $((${#node_list[@]} - 1)) && $i -eq $PROCS ]]; then
            echo sbatch -p RAM -t 7-00:00 -c 1 --mem=5G -w $node -J $PNAME -o slurm_out/slurm-$node-%j.out --mail-type=END,FAIL --mail-user=jerryjin@andrew.cmu.edu $SH_SCRIPT
            sbatch -p RAM -t 7-00:00 -c 1 --mem=5G -w $node -J $PNAME -o slurm_out/slurm-$node-%j.out --mail-type=END,FAIL --mail-user=jerryjin@andrew.cmu.edu $SH_SCRIPT
        else
            echo sbatch -p RAM -t 7-00:00 -c 1 --mem=5G -w $node -J $PNAME -o slurm_out/slurm-$node-%j.out $SH_SCRIPT
            sbatch -p RAM -t 7-00:00 -c 1 --mem=5G -w $node -J $PNAME -o slurm_out/slurm-$node-%j.out $SH_SCRIPT
        fi
        sleep 2
    done
done
