#!/bin/sh
# starts a SLURM job array of N instances
# ex.: pgo pso_cmr.py 8
#      will start an array of eight jobs running pso_cmr.py

function usage
{
  echo "Usage: pgo pyfile.py [num [-nb]]"
  echo "           num - Number of array tasks to start (default 1)"
  echo "           -nb - No backup of script"
  exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

SH_PATH=`dirname $0`
if [ "$SH_PATH" = "" ]; then
    SH_PATH=`dirname \`which $0\``
fi
SH_SCRIPT=${SH_PATH}/runpyfile.sh

BACK_DIR=runs
PYFILE=$1
PNAME=`expr substr \`basename $PYFILE\` 1 15`
PROCS=1

if [ $# -ge 2 ]; then PROCS=$2; fi
if [ "$3" = "-nb" ]; then NO_BACKUP=1; else NO_BACKUP=0; fi

if [ $NO_BACKUP -eq 0 ]; then
    echo Making backup:
    mkdir -p $BACK_DIR
    echo cp $PYFILE runs/${PYFILE}.`date +%y%b%d_%H%M`
    cp $PYFILE runs/${PYFILE}.`date +%y%b%d_%H%M`
fi

mkdir -p slurm_out

echo "Starting array of $PROCS job(s):"
echo sbatch --array=1-${PROCS} -J $PNAME $SH_SCRIPT $PYFILE
SUBMIT_OUT=$(sbatch --array=1-${PROCS} -J $PNAME $SH_SCRIPT $PYFILE)
echo "$SUBMIT_OUT"
JOB_ID=$(echo "$SUBMIT_OUT" | awk '{print $NF}')
sbatch --dependency=afterany:$JOB_ID ${SH_PATH}/notify_done.sh $JOB_ID
sbatch -J ${PNAME}_wd ${SH_PATH}/watchdog.sh $JOB_ID outfiles 15
