#!/bin/sh
# starts a SLURM job array of N instances
# ex.: pgo pso_cmr.py 8
#      will start an array of eight jobs running pso_cmr.py

function usage
{
  echo "Usage: pgo pyfile.py [num [-nb]]"
  echo "           num - Number of array tasks to start (default 1)"
  exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

SH_PATH=`dirname $0`
if [ "$SH_PATH" = "" ]; then
    SH_PATH=`dirname \`which $0\``
fi
SH_SCRIPT=${SH_PATH}/runpyfile.sh

PYFILE=$1
PNAME=`expr substr \`basename $PYFILE\` 1 15`
PROCS=1
if [ $# -ge 2 ]; then PROCS=$2; fi

mkdir -p slurm_out

echo "Starting array of $PROCS job(s):"
echo sbatch --array=1-${PROCS} -J $PNAME $SH_SCRIPT $PYFILE
SUBMIT_OUT=$(sbatch --array=1-${PROCS} -J $PNAME $SH_SCRIPT $PYFILE)
echo "$SUBMIT_OUT"
JOB_ID=$(echo "$SUBMIT_OUT" | awk '{print $NF}')
sbatch --dependency=afterany:$JOB_ID ${SH_PATH}/notify_done.sh $JOB_ID
sbatch -J ${PNAME}_wd ${SH_PATH}/watchdog.sh $JOB_ID outfiles 15
